### ISSUE TITLE
The Kindle version has too small math fonts

### ISSUE THREAD

**Issue by lorenzo-di-gregorio** [PacktPublishing/Bayesian-Analysis-with-Python-Second-Edition#1]
While I understand this might not be the best place to file the issue, I haven't found a better one.
The Kindle version of this book shows incredibly small math fonts, so I think that the generation of the eBook should be fixed and an update pushed through Amazon.

**Comment by aloctavodia** [comment]
Hi @lorenzo-di-gregorio I agree with you. I have been trying to convince Pack about a _second printing_  including fixing the errors listed in this errata https://github.com/aloctavodia/BAP

Unfortunately, I have not heard news from Packt in a while. Not sure what to do next.

**Comment by lorenzo-di-gregorio** [comment]
I have submitted an erratum on the website of Packt, given a bad review on Amazon.de because of the tiny formulas and flagged the eBook to Amazon.de because of bad quality.  If after review they will agree, they will issue a warning in the Kindle-Shop and suspend the sale.  If the issue does not get fixed, I'll have to return the eBook.  As reader, I can't do more.

I might understand Packt does not want to change the content because it is linked to the ISBN, but they must fix the formatting issues.  I'm not sure what contractual obligations you have, but as author you should have more possibilities of enforcing the editor to fulfill to the Amazon quality guidelines on eBooks, which you must be aware of.

I hope you can convince them to fix this and push an update very soon.

**Comment by aloctavodia** [comment]
Thanks for the feedback and thanks for your effort. In my experience Packt just do not care. I have been discussing formating issues even before the book was published. I hope your feedback helps, but I must admit I am skeptic.

**Comment by lorenzo-di-gregorio** [comment]
I had opened a CASE:405887 with Packt and got today feedback from Javed Sayyed that "We tried contacting our team, however we did not receive a response though."  I cannot figure what they mean with "our team", but if you know what they are talking about, you might try to follow up on the case above.

**Comment by aloctavodia** [comment]
Not sure either. 20 days ago, when you opened this issue, I sent an email to all the editors I was in contact while writing the book, still waiting of an answer. I will send them a remainder and I will add the case number.
