### ISSUE TITLE
README Links direct to the wrong book

### ISSUE THREAD

**Issue by tjburch** [PacktPublishing/Bayesian-Analysis-with-Python-Second-Edition#4]
The link for this book in your README appear is `https://www.amazon.com/dp/1788996348`, which directs to _Hands-On Data Science with SQL Server 2017: Perform end-to-end data analysis to gain efficient data insight_, not this textbook.

**Comment by aloctavodia** [comment]
thanks. It is fixed. Please remember to check this repo too https://github.com/aloctavodia/BAP
